### ISSUE TITLE
Missing Dependency: org.mockito.Answers

### ISSUE THREAD

**Issue by TooDaLoo** [microservices-practical/microservices-v1#1]
I'm sure I'm doing something wrong, or was supposed to install something.  But both v1 and v2 of the code samples give me this same error:

The type org.mockito.Answers cannot be resolved. It is indirectly referenced from required .class files	MultiplicationServiceTest.java	/social-multiplication-v2/src/test/java/microservices/book/multiplication/service

**Comment by mechero** [comment]
You only need to have the JDK 8 installed, so I don't think that's the problem. 

Is that the Maven's output or is it the IDE? Please try, from the console and inside the `social-multiplication` folder:
`mvnw clean package` (or `./mvnw clean package`, if you're on Linux/Mac) 

In v1, you should get test errors as expected. In v2 the build will succeed. 

If you still have that error when running Maven, try [cleaning the maven repository cache](https://stackoverflow.com/questions/7408545/how-do-you-clear-apache-mavens-cache).

If it's the IDE, I don't know the solution. But you can try googling the error with your IDE name to see how to clean it / modify the settings. 

Let me know if you can make it work.

**Comment by TooDaLoo** [comment]
Thank you!  I got it working by trying on a different PC that only had JDK 8 and Maven installed... no IDE of any kind.  I was then able to download V2 of your code and run the mvnw tests from the command line.  So I see the code is in good form, I just had something causing a conflict/error on my other PC.  I'll install Spring Tool Suite and check once more, but I think all should be good now.  Thank you for your help... am really enjoying the book so far.

**Comment by mechero** [comment]
Great! I'm glad you're enjoying the book!
